# M2608.001300 기계학습 기초 및 전기정보 응용<br> Assignment 4: Hidden Markov Model (HMM)

In [0]:
# Code from Chapter 16 of Machine Learning: An Algorithmic Perspective (2nd Edition)
# by Stephen Marsland (http://stephenmonika.net)

# You are free to use, change, or redistribute the code in any way you wish for
# non-commercial purposes, but please maintain the name of the original author.
# This code comes with no warranty of any kind.

# Stephen Marsland, 2008, 2014

# A basic Hidden Markov Model

## Setup
Check that Python 3.5 or later is installed (although Python 2.x may work, it is deprecated so we strongly recommend you use Python 3 instead).

In [0]:
# Python >=3.5 is required
import sys
assert sys.version_info >= (3, 5)

# Common imports
import numpy as np
from pandas import DataFrame

# to make this notebook's output stable across runs
np.random.seed(4)

## Problem 1. Evaluation problem
Get the probability of seeing an observation. <br>
We can use the following 2 algorithms:
<br>
* <font color=blue>*Forward algorithm*</font> (dynamic programming)
* <font color=blue>*Backward algorithm*</font> (dynamic programming)

In [0]:
scaling = False

In [0]:
"""
Let's denote the parameters of HMM model as,

pi : initial state probability
a : transition probability
b : emission probability
obs : observation sequence
"""
def HMMfwd(pi, a, b, obs):

	# TODO: Forward algorithm
	####################### YOUR CODE HERE #######################
	nStates = np.shape(b)[0]
	T = np.shape(obs)[0]

	alpha = np.zeros((nStates,T))
	alpha[:,0] = pi*b[:,obs[0]]

	for t in range(1,T):
		for s in range(nStates):
			alpha[s,t] = b[s,obs[t]] * np.sum(alpha[:,t-1] * a[:,s])
	c = np.ones((T))
 
	if scaling:
		for t in range(T):
			c[t] = np.sum(alpha[:,t])
			alpha[:,t] /= c[t]

	##############################################################
	return alpha,c

def HMMbwd(a, b, obs, c):

	# TODO: Backward algorithm
	####################### YOUR CODE HERE #######################
	nStates = np.shape(b)[0]
	T = np.shape(obs)[0]

	beta = np.zeros((nStates,T))
	beta[:,T-1] = 1.0

	for t in range(T-2,-1,-1):
		for s in range(nStates):
			beta[s,t] = np.sum(b[:,obs[t+1]] * beta[:,t+1] * a[s,:])

	for t in range(T):
		beta[:,t] /= c[t]
		
	beta[:,0] = b[:,obs[0]] * np.sum(beta[:,1] * pi)
 
	##############################################################
	return beta

## Problem 2. Decoding problem
Get the underlying state sequence of an observation. <br>
We can use the <font color=blue>*Viterbi algorithm*</font> (dynamic programming).

In [0]:
def Viterbi(pi, a, b, obs):

	# TODO: Viterbi algorithm
	####################### YOUR CODE HERE #######################
	nStates = np.shape(b)[0]
	T = np.shape(obs)[0]

	path = np.zeros(T)
	delta = np.zeros((nStates,T))
	phi = np.zeros((nStates,T))

	delta[:,0] = pi * b[:,obs[0]]
	phi[:,0] = 0

	for t in range(1,T):
		for s in range(nStates):
			delta[s,t] = np.max(delta[:,t-1]*a[:,s])*b[s,obs[t]]
			phi[s,t] = np.argmax(delta[:,t-1]*a[:,s])

	path[T-1] = np.argmax(delta[:,T-1])
	for t in range(T-2,-1,-1):
		path[t] = phi[int(path[t+1]),t+1]

	##############################################################
	return path, delta, phi

## Problem 3. Learning problem
Get the best parameters for the model. <br>
We can use the following 3 algorithms:
* *MLE* (maximum likelihood estimation)
* *Viterbi training* (different from Viterbi decoding)
* *Baum Welch algorithm* (a.k.a. forward-backward algorithm, uses expectation-maximization)

Here we implement the <font color=blue>*Baum Welch algorithm*</font>.

In [0]:
def BaumWelch(obs,nStates):

	T = np.shape(obs)[0]
	xi = np.zeros((nStates,nStates,T))

	# Initialise pi, a, b randomly
	pi = 1./nStates*np.ones((nStates))
	a = np.random.rand(nStates,nStates)
	b = np.random.rand(nStates,np.max(obs)+1)

	tol = 1e-5
	error = tol+1
	maxits = 100
	nits = 0

	# TODO: Baum Welch algorithm
	####################### YOUR CODE HERE #######################
	while ((error > tol) & (nits < maxits)):
		nits += 1
		oldpi = pi.copy()
		olda = a.copy()
		oldb = b.copy()

		# E step
		alpha,c = HMMfwd(pi,a,b,obs)
		beta = HMMbwd(a,b,obs,c) 

		for t in range(T-1):
			for i in range(nStates):
				for j in range(nStates):
					xi[i,j,t] = alpha[i,t]*a[i,j]*b[j,obs[t+1]]*beta[j,t+1]
			xi[:,:,t] /= np.sum(xi[:,:,t])

		# The last step has no b, beta in
		for i in range(nStates):
			for j in range(nStates):
				xi[i,j,T-1] = alpha[i,T-1]*a[i,j]
		xi[:,:,T-1] /= np.sum(xi[:,:,T-1])

		# M step
		for i in range(nStates):
			pi[i] = np.sum(xi[i,:,0])
			for j in range(nStates):
				a[i,j] = np.sum(xi[i,j,:T-1])/np.sum(xi[i,:,:T-1])
	
			for k in range(max(obs)):
				found = (obs==k).nonzero()
				b[i,k] = np.sum(xi[i,:,found])/np.sum(xi[i,:,:])

		error = (np.abs(a-olda)).max() + (np.abs(b-oldb)).max() 
	
	##############################################################
	return pi, a, b	

## Toy examples
Here are the parameters for HMM model.

In [0]:
transition_data = {'state': ['TV', 'Bar', 'Party', 'Study'],
                          'TV'    : [0.4, 0.3, 0.1, 0.2],
                          'Bar'   : [0.6, 0.05, 0.1, 0.25],
                          'Party' : [0.7, 0.05, 0.05, 0.2],
                          'Study' : [0.3, 0.4, 0.25, 0.05]}

emission_data = {'observation': ['tired', 'hangover', 'anxiety', 'good'],
                        'TV'    : [0.2, 0.1, 0.2, 0.5],
                        'Bar'   : [0.4, 0.2, 0.1, 0.3],
                        'Party' : [0.3, 0.4, 0.2, 0.1],
                        'Study' : [0.3, 0.05, 0.3, 0.35]}

transition_probability = DataFrame(transition_data, columns=['state', 'TV', 'Bar', 'Party', 'Study'])
emission_probability = DataFrame(emission_data, columns=['observation', 'TV', 'Bar', 'Party', 'Study'])

In [0]:
transition_probability

state   TV   Bar  Party  Study
0     TV  0.4  0.60   0.70   0.30
1    Bar  0.3  0.05   0.05   0.40
2  Party  0.1  0.10   0.05   0.25
3  Study  0.2  0.25   0.20   0.05

In [0]:
emission_probability

observation   TV  Bar  Party  Study
0       tired  0.2  0.4    0.3   0.30
1    hangover  0.1  0.2    0.4   0.05
2     anxiety  0.2  0.1    0.2   0.30
3        good  0.5  0.3    0.1   0.35

In [0]:
try:
    a = transition_probability.drop(['state'], axis=1).to_numpy()
    b = emission_probability.drop(['observation'], axis=1).to_numpy()
except:
    a = transition_probability.drop(['state'], axis=1).values
    b = emission_probability.drop(['observation'], axis=1).values

In [0]:
# Assume the initial state probabilites are all equal to 0.25
pi = np.array([0.25, 0.25, 0.25, 0.25])
# obs = np.array(['tired', 'tired', 'good', 'hangover', 'hangover', 'anxiety', 'hangover', 'good'])
obs = np.array([0, 0, 3, 1, 1, 2, 1, 3])

## Problem 4-1. 
What is the probability of seeing current observation?

In [0]:
####################### YOUR CODE HERE #######################
HMMfwd(pi,a,b,obs)
print("alpha")
print(alpha)
##############################################################

alpha
[[1.89262159e-203 1.44387932e-013 8.78402661e-003 1.68923798e-002
  8.33693765e-003 1.87045432e-017 1.21399924e-010 1.86552488e-009]
 [0.00000000e+000 2.14600677e-247 6.68727075e-015 2.08962962e-042
  4.01852348e-042 3.69440721e-003 4.44961851e-057 1.51292624e-010]
 [0.00000000e+000 8.66945614e-182 4.25366944e-037 6.68727050e-015
  2.07965281e-033 1.61902846e-204 3.69440707e-003 2.00960426e-023]
 [5.34279472e-001 1.81401788e-001 3.88693913e-002 7.51022066e-012
  1.45313428e-021 1.91257999e-146 7.55499312e-086 1.24567437e-003]]


## Problem 4-2.
Given the current observation, what is the most likely sequence of states?

In [0]:
####################### YOUR CODE HERE #######################
HMMfwd(pi,a,b,obs)
path, delta, phi = Viterbi(pi,a,b,obs)
print(path)
##############################################################

[3. 0. 0. 0. 0. 1. 0. 2.]


## Problem 4-3.
Given the current observation and the model, find the model parameters (transition probability, emission probability, initial state probability) that best fits the data.

In [0]:
####################### YOUR CODE HERE #######################
HMMfwd(pi,a,b,obs)
Viterbi(pi,a,b,obs)
pi, a, b = BaumWelch(obs,4)
print("transition probability")
print(a)
print("emission probability")
print(b)
print("initial state probability")
print(pi)
##############################################################

transition probability
[[5.56862626e-001 4.43137374e-001 2.97010935e-034 1.22448509e-059]
 [3.70771184e-008 6.53599065e-157 9.99999963e-001 5.26388985e-075]
 [3.78290256e-006 3.77264416e-007 3.10236529e-019 9.99995840e-001]
 [3.64516048e-001 3.23091217e-038 1.33736302e-034 6.35483952e-001]]
emission probability
[[7.41388348e-013 8.86273257e-001 4.02895560e-015 1.32842006e-001]
 [1.24318983e-209 5.36830636e-040 9.99999608e-001 1.04515242e-001]
 [1.21331636e-147 1.00000000e+000 6.53844968e-169 1.75336714e-002]
 [5.34279472e-001 3.04046753e-010 2.07113912e-125 3.37179831e-001]]
initial state probability
[2.55280731e-191 0.00000000e+000 0.00000000e+000 1.00000000e+000]
